### ISSUE TITLE
Unable to connect and manage CanoKey via yubico-piv-tool and ykman.

### ISSUE THREAD

**Issue by xmmazhao** [canokeys/canokey-nrf52#10]
When using the PIV functionality on a Windows system, I am unable to connect and manage CanoKey through the Yubico-PIV-Tool and ykman, encountering messages such as "Failed to connect to YubiKey" and "error in pcsc." Could you please specify which versions of the Yubico-PIV-Tool and ykman are required to manage CanoKey?

**Comment by xmmazhao** [comment]
Commind: yubico-piv-tool -r ostar -a set-ccc
Error Info: Failed to connect to yubikey: Error in PCSC call.

**Comment by xmmazhao** [comment]
> Commind: yubico-piv-tool -r ostar -a set-ccc Error Info: Failed to connect to yubikey: Error in PCSC call.

windows   ubuntu   has same error info

**Comment by z4yx** [comment]
Try pcsc_scan command. Your device may not be detected by pcscd at all.

**Comment by xmmazhao** [comment]
root@ostar-VMware-Virtual-Platform:~# pcsc_scan
PC/SC device scanner
V 1.7.1 (c) 2001-2022, Ludovic Rousseau <ludovic.rousseau@free.fr>
Using reader plug'n play mechanism
Scanning present readers...
0: VMware Virtual USB CCID 00 00
 
Wed Aug 28 13:27:05 2024
 Reader 0: VMware Virtual USB CCID 00 00
  Event number: 0
  Card state: Card inserted, 
  ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99

ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99
+ TS = 3B --> Direct Convention
+ T0 = F7, Y(1): 1111, K: 7 (historical bytes)
  TA(1) = 11 --> Fi=372, Di=1, 372 cycles/ETU
    10752 bits/s at 4 MHz, fMax for Fi = 5 MHz => 13440 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 65 --> Block Waiting Integer: 6 - Character Waiting Integer: 5
+ Historical bytes: 43 61 6E 6F 6B 65 79
  Category indicator byte: 43 (proprietary format)
+ TCK = 99 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99
        Canokey (Other)
        http://canokeys.org/



the device is nrf52840 dongle

**Comment by xmmazhao** [comment]
the device is  nrf52840 dongle

root@ostar-VMware-Virtual-Platform:~# pcsc_scan
PC/SC device scanner
V 1.7.1 (c) 2001-2022, Ludovic Rousseau <ludovic.rousseau@free.fr>
Using reader plug'n play mechanism
Scanning present readers...
0: VMware Virtual USB CCID 00 00
 
Wed Aug 28 13:29:07 2024
 Reader 0: VMware Virtual USB CCID 00 00
  Event number: 0
  Card state: Card inserted, 
  ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99

ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99
+ TS = 3B --> Direct Convention
+ T0 = F7, Y(1): 1111, K: 7 (historical bytes)
  TA(1) = 11 --> Fi=372, Di=1, 372 cycles/ETU
    10752 bits/s at 4 MHz, fMax for Fi = 5 MHz => 13440 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 65 --> Block Waiting Integer: 6 - Character Waiting Integer: 5
+ Historical bytes: 43 61 6E 6F 6B 65 79
  Category indicator byte: 43 (proprietary format)
+ TCK = 99 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99
        Canokey (Other)
        http://canokeys.org/

**Comment by xmmazhao** [comment]
This operation will be done inside the virtual machine, and later tonight, I can take a screenshot of the smart card information recognized under the physical Ubuntu machine. The name of the smart card is also visible and normal under the physical machine.

**Comment by z4yx** [comment]
If pcsc_scan shows "VMware Virtual USB CCID ", you should use this name as value of `-r` of yubico-piv-tool

**Comment by xmmazhao** [comment]
Thank you, boss, I succeeded.  Thank you very much!
you can close this issue.
