### ISSUE TITLE
Problem with sign with the key

### ISSUE THREAD

**Issue by BH2VSQ** [canokeys/canokey-nrf52#2]
I can import the RSA4096 PGP key to the canokey. But when I sign with it, it always return the sign failled. I found that Nrf52840 dongle has a button connected to P0.11. Should I click it for the same thing for the key work normally?

**Comment by NekoMio** [comment]
Same problem, any solution?

**Comment by meow-plus** [comment]
same problem

**Comment by z4yx** [comment]
The canokey-core library has been updated to the latest version, RSA4096 should work now. I have tested this feature on NRF52840 dongle.

**Comment by NekoMio** [comment]
Thanks for your great job.
I noticed that you modified the flash layout in recent commits.(https://github.com/canokeys/canokey-nrf52/commit/83bdc5dbc9e83e50b1416ea8f515719847dc7f7)
Is it possible to update the firmware directly without losing data?

**Comment by z4yx** [comment]
Since the core library has changed file structures, it's impossible to upgrade firmware while keeping data. So I changed the base address of FS directly.

**Comment by z4yx** [comment]
Generally, hardware security keys should not allow firmware upgrade. So backward compatibility is not taken into consideration during the development of canokey-core.

**Comment by NekoMio** [comment]
OK, Thanks.
