### ISSUE TITLE
Problem while using key

### ISSUE THREAD

**Issue by mcxufly** [canokeys/canokey-nrf52#4]
When I use the latest firmware([c2fe97f9](https://github.com/canokeys/canokey-nrf52/commit/c2fe97f92488213ad0621673c825e3ed02ef7df2)) on `makerdiary nRF52840 MDK USB Dongle w/ Case`, pressing the button does not correspond to a Touch operation but a reconnection, causing the passkey to not work properly.

Press 2 times will boot in to bootloader of the nRF52.

And I can't enable `HOTP on touch`.

**Comment by mcxufly** [comment]
How do I accomplish touch operation on this device.

**Comment by z4yx** [comment]
I'm not sure if the pin connection of your dongle is the same as the Nordic dongle. You may check the pin number of the button, and modify the definition of BUTTON_1 in https://github.com/canokeys/canokey-nrf52/blob/master/config/boards/nordic/pca10059.h

**Comment by mcxufly** [comment]
I have already solved this problem.

The problem is in two places.

1. In file [CMakeLists.txt](https://github.com/canokeys/canokey-nrf52/blob/master/CMakeLists.txt) line 26, `-DCONFIG_GPIO_AS_PINRESET` will make the button on this board work as a reset button.
2. In file [pca10059.h](https://github.com/canokeys/canokey-nrf52/blob/master/config/boards/nordic/pca10059.h) the pin connection is wrong for `makerdiary nRF52840 MDK USB Dongle`

So, in order for `makerdiary nRF52840 MDK USB Dongle` to work properly a new board config file needs to be added.
