### ISSUE TITLE
Question about compiling Adafruit_nRF52_Bootloader for Ebyte E104-BT5040U

### ISSUE THREAD

**Issue by xiaofami** [canokeys/canokey-nrf52#7]
I've successfully compiled canokey-nrf52 firmware for my **Ebyte E104-BT5040U** and have **canokey.hex** and **canokey_flash.uf2** at hand . According to README, I should compile and flash **Adafruit_nRF52_Bootloader** in order to flash **canokey_flash.uf2**. However, it seems that **Adafruit_nRF52_Bootloader** does not support **Ebyte E104-BT5040U** currently and I got stuck here as a result. How does everyone else compile **Adafruit_nRF52_Bootloader**? Any instructions would be greatly appreciated.

BTW, according to [为 nRF52840 Dongle 刷入 CanoKey 固件](https://kwaa.dev/canokey-nrf52), it seems that we could flash **canokey.hex** direclty with [nRF Connect for Desktop](https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-desktop). Is there noticable difference between two methods ? The size of **canokey.hex** is about 40% bigger than **canokey_flash.uf2** as far as I'm concerned.

**Comment by z4yx** [comment]
It depends on which bootloader was installed on your board. Please ask your vendor for compatible host tools.
canokey.hex is a raw firmware file in text format, so it's bigger than binary formats. Flash tools such as J-Link and DAP-Link recognize this format.
